import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { cn } from "~/lib/utils";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Vanishtype",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} font-mono min-h-screen antialiased`}>
        <div className="flex min-h-screen flex-col mx-auto max-w-7xl px-4 py-8">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
